name: VoteReward
main: me.adixe.votereward.VoteReward
version: 3.1.1
api-version: 1.18
authors: [Adixe]
description: Reward players for voting for the server.
commands:
  votereward:
    aliases:
      - vr
permissions:
  votereward.command:
    default: true
  votereward.reward:
    default: true
  votereward.check:
    default: op
  votereward.reload:
    default: op