name: VoteReward
main: me.adixe.votereward.VoteReward
version: 2.2
api-version: 1.13
author: Adixe
description: Reward players for voting for the server.
commands:
  votereward:
    aliases:
      - vr
permissions:
  votereward.reward:
    default: true
  votereward.check:
    default: op
  votereward.reload:
    default: op