#
# VoteReward
# Reward players for voting for the server.
#
# Source code and documentation: https://github.com/dudekm/VoteReward
#
# Spigot: Adixe
# Discord: adixepl
# GitHub: AdixePL
#
Servers:
  Server1:
    Address: https://lista-serwerow.emecz.pl
    Uuid: b23d452d-fbf1-47cf-a1d9-801a3e0bb516
    RewardCommands:
      - xp add %player_name% 100
      - give %player_name% diamond
  Server2:
    Address: https://lista-minecraft.pl
    Uuid: a5a29c24-6514-472d-add0-0b2be060e277
    RewardCommands:
      - xp add %player_name% 100
      - give %player_name% emerald