# __      __   _         _____                            _
# \ \    / /  | |       |  __ \                          | |
#  \ \  / /__ | |_ ___  | |__) |_____      ____ _ _ __ __| |
#   \ \/ / _ \| __/ _ \ |  _  // _ \ \ /\ / / _` | '__/ _` |
#    \  / (_) | ||  __/ | | \ \  __/\ V  V / (_| | | | (_| |
#     \/ \___/ \__\___| |_|  \_\___| \_/\_/ \__,_|_|  \__,_|
#
# Reward players for voting for the server.
#
# Source code and documentation: https://github.com/dudekm/VoteReward
#
# Spigot: Adixe
# Discord: adixepl
# GitHub: AdixePL
#
servers:
  server1:
    address: https://lista-serwerow.emecz.pl
    uuid: b23d452d-fbf1-47cf-a1d9-801a3e0bb516
    reward-commands:
      - xp add %player_name% 100
      - give %player_name% diamond
  server2:
    address: https://lista-minecraft.pl
    uuid: a5a29c24-6514-472d-add0-0b2be060e277
    reward-commands:
      - xp add %player_name% 100
      - give %player_name% emerald